branches:
  only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

language: julia

os:
  - linux

julia:
  - 1.0
  - 1.1
  - 1.2

notifications:
  email: false

sudo: false

addons:
  # mariadb: '10.0'
  homebrew:
    packages:
    - mariadb
    update: true

services:
  - mysql

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then . ./ci/travis/before_install-osx.sh; fi
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`mysql_config --libs | cut -d ' ' -f1 | sed 's/-L//'`

after_success:
  - julia -e 'import Pkg; Pkg.instantiate(); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

matrix:
  allow_failures:
  - julia: 1.2

jobs:
  include:
    - stage: test
      os: osx
      julia: 1.1
      script:
        - julia -e 'import Pkg; Pkg.build(); Pkg.test(coverage=false);'
      after_success: skip
    - stage: example
      os: linux
      julia: 1.1
      script:
        - julia -e 'import Pkg; Pkg.instantiate(); include(joinpath(@__DIR__, "examples", "runexamples.jl"))'
    - stage: deploy documentation
      julia: 1.1
      os: linux
      script:
        - julia -e 'import Pkg; Pkg.instantiate(); Pkg.add("Documenter"); Pkg.add("Literate"); include(joinpath("docs", "make.jl"))'
      after_success: skip
