branches:
  only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

language: julia

os:
  - linux

julia:
  - 1.0
  - 1.1
  - 1.2

notifications:
  email: false

addons:
  mariadb: '10.4'

after_success:
  - julia -e 'import Pkg; Pkg.instantiate(); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - # continue
      os: osx
      julia: 1.1
      script:
        - julia -e 'import Pkg; Pkg.build(); Pkg.test(coverage=false);'
      after_success: skip
    - stage: examples
      os: linux
      julia: 1.1
      env: GROUP=Examples
      script:
        - julia -e 'import Pkg; Pkg.instantiate(); include(joinpath(@__DIR__,"examples","runexamples.jl"))'
    - stage: deploy docs
      julia: 1.1
      os: linux
      script:
        - julia -e 'import Pkg; Pkg.instantiate(); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
      after_success: skip
